# services:
#   - type: web
#     name: ecommerce-api
#     env: python
#     plan: free
#     buildCommand: pip install -r requirements.txt
#     startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: ecommerce-db
#           property: connectionString

#       - key: SECRET_KEY
#         generateValue: true

#       - key: ALGORITHM
#         value: HS256

#       - key: ACCESS_TOKEN_EXPIRE_MINUTES
#         value: 30

# databases:
#   - name: ecommerce-db
#     plan: free

services:
  - type: web
    name: ecommerce-api
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /health

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: ALGORITHM
        value: HS256

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

      - key: ENV
        value: production

databases:
  - name: ecommerce-db
    plan: free